---
# https://github.com/mozilla/policy-templates/tree/master/mac

- name: Macos | Enable enterprise policies
  community.general.osx_defaults:
    domain: /Library/Preferences/org.mozilla.firefox
    key: EnterprisePoliciesEnabled
    type: bool
    value: true
  become: yes

- name: Macos | Ensure distribution directory exists
  ansible.builtin.file:
    dest: "{{ fxpolicies_path | dirname }}"
    mode: '0755'
    state: directory

- name: Macos | Enable enterprise policies
  ansible.builtin.template:
    src: "{{ fxpolicies_template }}.j2"
    dest: "{{ fxpolicies_path }}"
    mode: '0644'
