---

- name: Import unix
  ansible.builtin.import_tasks: unix.yml
  when: ansible_os_family != "Windows"

- name: Import darwin
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Import windows-firefox
  ansible.builtin.import_tasks: windows-firefox.yml
  when: ansible_os_family == "Windows"
