---

- import_tasks: unix.yml
  when: ansible_os_family != "Windows"

- import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- import_tasks: windows-firefox.yml
  when: ansible_os_family == "Windows"
