---
# https://github.com/pyllyukko/user.js/
# https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences#Changing_defaults

- name: Install template userjs
  ansible.builtin.template:
    src: "{{ fx_template_userjs }}"
    dest: "{{ fxjs_path }}"
    mode: '0644'
    backup: "{{ firefoxconfig_backup | default(false) }}"
  when: fx_template_userjs and not fx_harden_userjs

- name: Harden userjs
  when: fx_harden_userjs
  block:
    - name: Check if firefox.js exists
      ansible.builtin.stat:
        path: "{{ fxjs_path }}-pyllyukko"
      register: fxjsp

    - name: Download pyllyukko harden user.js
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/pyllyukko/user.js/b95fc165d72d49a8202eb56e0f2cf6bb273a801b/user.js'
        checksum: 'sha256:330c54106c483a89167a90f0a6d3442b83f3407af000e632bdef6f105c5f2596'
        dest: "{{ fxjs_path }}-pyllyukko"
        mode: '0644'
        backup: yes
      when: not fxjsp.stat.exists

    - name: Configure as default pref
      ansible.builtin.replace:
        dest: "{{ fxjs_path }}-pyllyukko"
        regexp: 'user_pref\('
        replace: 'pref('
        backup: yes
      when: not fxjs_lockpref

    - name: Configure as locked pref
      ansible.builtin.replace:
        dest: "{{ fxjs_path }}-pyllyukko"
        regexp: 'user_pref\('
        replace: 'lockPref('
        backup: yes
      when: fxjs_lockpref

    - name: Install pyllyukko harden user.js
      ansible.builtin.copy:
        src: "{{ fxjs_path }}-pyllyukko"
        dest: "{{ fxjs_path }}"
        mode: '0644'
        backup: yes
        remote_src: true

## cas.sh ? only apply to user profile ~/.mozilla/firefox/XXXXXXXX.current_profile
# https://github.com/pyllyukko/user.js/blob/master/CAs.md
# copy cert8.db to browser/defaults/profile
# https://mike.kaply.com/2013/05/13/more-major-changes-coming-in-firefox-21/
# https://mike.kaply.com/2012/03/30/customizing-firefox-default-profiles/
